name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract Commit SHA
        id: extract_sha
        run: echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
      - name: Trigger Render Deploy Hook
        run: |
          DEPLOY_HOOK_URL=${{ secrets.DEPLOY_HOOK_URL }}
          COMMIT_SHA=${{ steps.extract_sha.outputs.commit_sha }}
          curl -X POST "$DEPLOY_HOOK_URL&ref=$COMMIT_SHA"
      - name: Wait for 3 minutes to complete deploy
        run: sleep 180

  run-tests:
    needs: deploy-stage
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Change to tests directory
      run: cd tests
      
    - name: Execute UI tests
      run: dotnet test
      working-directory: tests
        
  deploy-prod:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID_PROD }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
